code-critics
ruleCollectionProtocolRuleV1FalsePositive

	<ignoreForCoverage>
	^ #(#(#(#RGMethodDefinition #(#'XMLReport class' #loadAllFrom: #true)) #'2024-06-25T15:07:42.22704+02:00') #(#(#RGMethodDefinition #(#'TestCatalog class' #removeDuplicates: #true)) #'2024-07-16T16:36:47.369125+02:00') #(#(#RGMethodDefinition #(#TestCombinationCatalog #combinationsWellReparted #false)) #'2024-07-24T16:31:55.341688+02:00') #(#(#RGMethodDefinition #(#'TestCatalog class' #fromXMLCatalog: #true)) #'2024-07-26T11:14:57.343368+02:00') #(#(#RGMethodDefinition #(#'XMLCatalog class' #loadAllFrom: #true)) #'2024-07-26T11:15:49.585754+02:00') )